dataset_path: "../data/dataset.csv"
#label_mapping_path: "../data/mapping_19_09.csv"
label_mapping_path: "../data/label_mapping_only_single.csv"
graph_evolution_path: "../data/graph_evolution.csv"
sample_path: "../data/sample_overview.csv"
